/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/components/App.vue')['default']
    Copy: typeof import('./src/components/Copy.vue')['default']
    GithubRepoCard: typeof import('./src/components/GithubRepoCard.vue')['default']
    MyInput: typeof import('./src/components/ui/MyInput.vue')['default']
    RepoLike: typeof import('./src/components/RepoLike.vue')['default']
    ReposList: typeof import('./src/components/ReposList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollBar: typeof import('./src/components/ui/ScrollBar.vue')['default']
  }
}
